Correçao bug no comando de gerar componente; tratatica de erro caso a pasta exista

diff --git a/vuets b/vuets
--- a/vuets
+++ b/vuets
@@ -17,7 +17,7 @@ function help(){
 	echo -e "\033[1;38m vuets c [name] [diretório] \033[0m"
 	echo ""
 	echo -e "\033[1;37m Exemplo de uso component: \033[0m"
-	echo -e "\033[1;32m $ vuets c home view/home \033[0m"
+	echo -e "\033[1;32m $ vuets c home views \033[0m"
 	echo "" # modulo
 	echo -e "\033[1;37m Criar Vuex modulo ( m | -m | module ): \033[0m"
 	echo -e "\033[1;38m vuets m [name] \033[0m"
@@ -31,11 +31,11 @@ function help(){
 
 function gerateHMTL(){
 	echo -e "<template>
-	<div> 
+	<div>
 		<h1>$1 is ready!</h1>
 	</div>
 </template>
-	
+
 <script lang=\"ts\" src=\"./$1.ts\"></script>
 
 <style scoped>
@@ -59,7 +59,11 @@ function gerateCSS(){
 
 function gerateComponent(){
 	fileName="$(upperCaseFirst $1)"
-	mkdir $isDir/$2/$1 2>&1&> /dev/null
+	mkdir "$isDir/$2/$1" #2>&1&> /dev/null
+	if [ $? != 0 ]; then
+		echo -e "\033[0;31mError(directory exist): Operação cancelada. \033[0m"
+		exit
+	fi
 	gerateHMTL $1 $2
   gerateTS $1 $2
   gerateCSS $1 $2
@@ -79,10 +83,10 @@ function upperCaseFirst(){
 
 function interfaceObject(){
 	interface="export interface $objectName {"
-	
+
 	for x in "${arrayAttr[@]}"
 	do
-		interface="$interface\n 
+		interface="$interface\n
 		 $x"
 	done
 
@@ -91,8 +95,8 @@ function interfaceObject(){
 
 function interfaceState(){
 	interface="$interface\nexport interface $objectName""State {\n"
-	
-	interface="$interface 
+
+	interface="$interface
 	$moduleaName: $objectName\n
 		loader: boolean\n"
 
@@ -119,7 +123,7 @@ function gerateState(){
 function gerateGetters(){
 	stateParam="state: $objectName""State"
 	echo -e "import { $objectName, $objectName""State } from './$moduleaName'
-	
+
 export default {
 	$moduleaName($stateParam): $objectName {
 		return state.$moduleaName
@@ -135,7 +139,7 @@ export default {
 function gerateMutations(){
 	mutationParam="state: $objectName""State"
 	echo -e "import { $objectName, $objectName""State } from './$moduleaName'
-	
+
 export default {
 	set$objectName($mutationParam, $moduleaName: $objectName): void {
 		state.$moduleaName = $moduleaName
@@ -153,7 +157,7 @@ function gerateActions(){
 	echo -e "import { ActionContext } from 'vuex'
 import { $objectName""State } from './$moduleaName'
 import { api, /*setToken, clearToken*/ } from '@/services/api'
-	
+
 export default {
 	fetch$objectName($actionsParam): void {
 		api.get('/$moduleaName').then((response) => {
@@ -189,12 +193,12 @@ echo "GERATE => $dir/index.ts"
 case "$1" in
   "c"|"-c"|"component")
 		if [ "$2" != '' ]; then # verifica parâmetro 2 "nome" do componente
-      if [ "$3" != '' ]; then # verifica  parâmetro 3 => "diretório(view ou componet)" onde vai ser criado
-				gerateComponent $2 $3				
+      if [ "$3" != '' ]; then # verifica  parâmetro 3 => "diretório(views ou componet)" onde vai ser criado
+				gerateComponent $2 $3
     	fi
     fi
 		help
-  ;;  
+  ;;
   "m"|"-m"|"module")
 		if [ "$2" != '' ]; then # verifica parâmetro 2 "nome" do componente
 			echo "gerar"
@@ -205,7 +209,11 @@ case "$1" in
 			getFileDir="$PWD/src/store/$2"
 			dir="$PWD/src/store/modules/$2"
 			#criar pasta
-			mkdir $dir 2>&1&> /dev/null
+			mkdir $dir #2>&1&> /dev/null
+			if [ $? != 0 ]; then
+				echo -e "\033[0;31mError(directory exist): Operação cancelada. \033[0m"
+				exit
+			fi
 			#transforma o texto em array
 			mapfile -t arrayAttr < $getFileDir
 			#gerar arquivos
@@ -219,18 +227,13 @@ case "$1" in
 			echo -e "\033[1;33m * Atenção vc ainda tem que referênciar $moduleaName em @/store/index.ts* \033[0m"
 			echo -e "\033[1;32m * Modulo gerado * \033[0m"
     fi
-  ;;  
+  ;;
   ""|"-h"|"help"|"-help"|"--help")
 		help
-  ;;  
+  ;;
   *)
 		help
   ;;
 esac
 
 help
-
-
-
-
-
